let nationalities = {
  'plural': 'Singular',
  'nationalities': 'Nationality',
  'afghan': 'Afghanistan',
  'argentineargentinian': 'Argentina',
  'australian': 'Australia',
  'belgian': 'Belgium',
  'bolivian': 'Bolivia',
  'brazilian': 'Brazil',
  'cambodian': 'Cambodia',
  'cameroonian': 'Cameroon',
  'canadian': 'Canada',
  'chilean': 'Chile',
  'chinese': 'China',
  'colombian': 'Colombia',
  'costa rican': 'Costa Rica',
  'cuban': 'Cuba',
  'danish': 'Denmark',
  'dominican': 'Dominican Republic',
  'ecuadorian': 'Ecuador',
  'egyptian': 'Egypt',
  'salvadorian': 'El Salvador',
  'english': 'England',
  'estonian': 'Estonia',
  'ethiopian': 'Ethiopia',
  'finnish': 'Finland',
  'french': 'France',
  'german': 'Germany',
  'ghanaian': 'Ghana',
  'greek': 'Greece',
  'guatemalan': 'Guatemala',
  'haitian': 'Haiti',
  'honduran': 'Honduras',
  'indonesian': 'Indonesia',
  'iranian': 'Iran',
  'irish': 'Ireland',
  'israeli': 'Israel',
  'italian': 'Italy',
  'japanese': 'Japan',
  'jordanian': 'Jordan',
  'kenyan': 'Kenya',
  'laotian': 'Laos',
  'latvian': 'Latvia',
  'lebanese': 'Lebanon',
  'lithuanian': 'Lithuania',
  'malaysian': 'Malaysia',
  'mexican': 'Mexico',
  'moroccan': 'Morocco',
  'dutch': 'Netherlands',
  'new zealander': 'New Zealand',
  'nicaraguan': 'Nicaragua',
  'norwegian': 'Norway',
  'panamanian': 'Panama',
  'paraguayan': 'Paraguay',
  'peruvian': 'Peru',
  'filipino': 'Philippines',
  'polish': 'Poland',
  'portuguese': 'Portugal',
  'puerto rican': 'Puerto Rico',
  'romanian': 'Romania',
  'russian': 'Russia',
  'saudi': 'Saudi Arabia',
  'scottish': 'Scotland',
  'korean': 'South Korea',
  'spanish': 'Spain',
  'swedish': 'Sweden',
  'swiss': 'Switzerland',
  'taiwanese': 'Taiwan',
  'tajik': 'Tajikistan',
  'thai': 'Thailand',
  'turkish': 'Turkey',
  'ukrainian': 'Ukraine',
  'british': 'United Kingdom',
  'american': 'United States',
  'uruguayan': 'Uruguay',
  'venezuelan': 'Venezuela',
  'vietnamese': 'Vietnam',
  'welsh': 'Wales'
};

let regions = {
  'european': 'Europe',
  'asian': 'Asia',
  'african': 'Africa'
}

module.exports = { nationalities, regions };